M48
; DRILL file {KiCad 8.0.1} date 2024-04-17T00:31:54+1200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-17T00:31:54+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.2962Y-2.202
X3.2962Y-2.4296
T2
X3.215Y-1.6107
X3.215Y-3.3007
X4.905Y-1.6107
X4.905Y-3.295
M30
